"""Type stubs for the lr native extension (_lr)."""

from __future__ import annotations

import enum
import os
import pathlib
from typing import Callable, Sequence, overload

import numpy
from numpy.typing import NDArray

# Anything exposing the buffer protocol: numpy arrays, bytes, bytearray, memoryview.
from collections.abc import Buffer

# Pure-Python submodules imported by lr/__init__.py (gui and transforms are typed in their own .py files;
# engine, the engine's preassembled renderer, in engine.pyi).
from . import engine as engine, gui as gui, transforms as transforms

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class Format(enum.Enum):
    UNDEFINED = ...
    R8_UNORM = ...
    R8G8B8A8_UNORM = ...
    R8G8B8A8_SRGB = ...
    B8G8R8A8_UNORM = ...
    B8G8R8A8_SRGB = ...
    R16_SFLOAT = ...
    R16G16_SFLOAT = ...
    R16G16B16A16_SFLOAT = ...
    R16G16B16A16_UNORM = ...
    R32_SFLOAT = ...
    R32G32_SFLOAT = ...
    R32G32B32_SFLOAT = ...
    R32G32B32A32_SFLOAT = ...
    R32_UINT = ...
    D32_SFLOAT = ...

class BufferUsage(enum.IntFlag):
    TRANSFER_SRC = ...
    TRANSFER_DST = ...
    UNIFORM = ...
    STORAGE = ...
    INDEX = ...
    VERTEX = ...
    INDIRECT = ...

class ImageUsage(enum.IntFlag):
    TRANSFER_SRC = ...
    TRANSFER_DST = ...
    SAMPLED = ...
    STORAGE = ...
    COLOR_ATTACHMENT = ...
    DEPTH_STENCIL_ATTACHMENT = ...

class Stage(enum.IntFlag):
    VERTEX = ...
    FRAGMENT = ...
    COMPUTE = ...
    ALL_GRAPHICS = ...

class Topology(enum.Enum):
    POINT_LIST = ...
    LINE_LIST = ...
    LINE_STRIP = ...
    TRIANGLE_LIST = ...
    TRIANGLE_STRIP = ...

class LoadOp(enum.Enum):
    LOAD = ...
    CLEAR = ...
    DONT_CARE = ...

class BlendMode(enum.Enum):
    OPAQUE = ...
    ALPHA = ...
    PREMULTIPLIED_ALPHA = ...
    ADDITIVE = ...

class PolygonMode(enum.Enum):
    FILL = ...
    LINE = ...
    POINT = ...

class CullMode(enum.IntFlag):
    NONE = ...
    FRONT = ...
    BACK = ...
    FRONT_AND_BACK = ...

class FrontFace(enum.Enum):
    COUNTER_CLOCKWISE = ...
    CLOCKWISE = ...

class CompareOp(enum.Enum):
    NEVER = ...
    LESS = ...
    EQUAL = ...
    LESS_OR_EQUAL = ...
    GREATER = ...
    NOT_EQUAL = ...
    GREATER_OR_EQUAL = ...
    ALWAYS = ...

class PassType(enum.Enum):
    GEOMETRY = ...
    FULLSCREEN = ...
    COMPUTE = ...
    CUSTOM = ...

class Key(enum.Enum):
    """Keyboard keys (GLFW key codes)."""
    A = ...
    B = ...
    C = ...
    D = ...
    E = ...
    F = ...
    G = ...
    H = ...
    I = ...
    J = ...
    K = ...
    L = ...
    M = ...
    N = ...
    O = ...
    P = ...
    Q = ...
    R = ...
    S = ...
    T = ...
    U = ...
    V = ...
    W = ...
    X = ...
    Y = ...
    Z = ...
    DIGIT_0 = ...
    DIGIT_1 = ...
    DIGIT_2 = ...
    DIGIT_3 = ...
    DIGIT_4 = ...
    DIGIT_5 = ...
    DIGIT_6 = ...
    DIGIT_7 = ...
    DIGIT_8 = ...
    DIGIT_9 = ...
    F1 = ...
    F2 = ...
    F3 = ...
    F4 = ...
    F5 = ...
    F6 = ...
    F7 = ...
    F8 = ...
    F9 = ...
    F10 = ...
    F11 = ...
    F12 = ...
    SPACE = ...
    ESCAPE = ...
    ENTER = ...
    TAB = ...
    BACKSPACE = ...
    DELETE = ...
    LEFT = ...
    RIGHT = ...
    UP = ...
    DOWN = ...
    LEFT_SHIFT = ...
    RIGHT_SHIFT = ...
    LEFT_CONTROL = ...
    RIGHT_CONTROL = ...
    LEFT_ALT = ...
    RIGHT_ALT = ...

class MouseButton(enum.Enum):
    LEFT = ...
    RIGHT = ...
    MIDDLE = ...

class ShaderStage(enum.Enum):
    VERTEX = ...
    FRAGMENT = ...
    COMPUTE = ...

# ---------------------------------------------------------------------------
# Handles
# ---------------------------------------------------------------------------

class ImageHandle:
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

class BufferHandle:
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

class PassHandle:
    def __bool__(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...

# ---------------------------------------------------------------------------
# Value types
# ---------------------------------------------------------------------------

class Extent:
    @staticmethod
    def swapchain() -> Extent:
        """Same size as the swapchain (the default)."""
        ...
    @staticmethod
    def absolute(width: int, height: int) -> Extent:
        """A fixed size in pixels."""
        ...
    @staticmethod
    def relative(numerator: int, denominator: int) -> Extent:
        """A fraction of the swapchain size, e.g. relative(1, 2) for half-res."""
        ...

class VertexBinding:
    binding: int
    stride: int
    def __init__(self, binding: int, stride: int, per_instance: bool = False) -> None: ...

class VertexAttribute:
    location: int
    binding: int
    format: Format
    offset: int
    def __init__(self, location: int, format: Format, offset: int = 0, binding: int = 0) -> None: ...

# ---------------------------------------------------------------------------
# Command buffer
# ---------------------------------------------------------------------------

class CommandBuffer:
    """Thin wrapper around a Vulkan command buffer. Only valid during a pass's execute callback."""

    def draw(
        self,
        vertex_count: int,
        instance_count: int = 1,
        first_vertex: int = 0,
        first_instance: int = 0,
    ) -> None:
        """Record a non-indexed draw call."""
        ...

    def draw_indexed(
        self,
        index_count: int,
        instance_count: int = 1,
        first_index: int = 0,
        vertex_offset: int = 0,
        first_instance: int = 0,
    ) -> None:
        """Record an indexed draw call."""
        ...

    def dispatch(self, x: int, y: int = 1, z: int = 1) -> None:
        """Dispatch a compute shader."""
        ...

    def set_viewport(
        self,
        x: float,
        y: float,
        width: float,
        height: float,
        min_depth: float = 0.0,
        max_depth: float = 1.0,
    ) -> None: ...

    def set_scissor(self, x: int, y: int, width: int, height: int) -> None: ...

# ---------------------------------------------------------------------------
# Pass context
# ---------------------------------------------------------------------------

class PassContext:
    """Handed to a pass's execute callback. Only valid during that call — don't keep it."""

    @property
    def cmd(self) -> CommandBuffer:
        """The command buffer to record draw/dispatch calls into."""
        ...

    @property
    def rendering_extent(self) -> tuple[int, int]:
        """Current render-target size as (width, height)."""
        ...

    def extent(self, image: ImageHandle) -> tuple[int, int]:
        """Size of a specific image as (width, height)."""
        ...

    def push_constants(
        self,
        stages: Stage,
        data: Buffer,
        offset: int = 0,
    ) -> None:
        """Push `data` (e.g. a float32 numpy array) into the pass's push-constant block."""
        ...

    def draw_indirect(
        self,
        buffer: BufferHandle,
        draw_count: int = 1,
        offset: int = 0,
        stride: int = 16,
    ) -> None:
        """vkCmdDrawIndirect from a buffer declared with indirect_buffer(); commands are 4 uint32s
        (vertex_count, instance_count, first_vertex, first_instance)."""
        ...

    def draw_indexed_indirect(
        self,
        buffer: BufferHandle,
        draw_count: int = 1,
        offset: int = 0,
        stride: int = 20,
    ) -> None:
        """vkCmdDrawIndexedIndirect; commands are 5 x 4 bytes (index_count, instance_count, first_index,
        vertex_offset, first_instance)."""
        ...

    def dispatch_indirect(self, buffer: BufferHandle, offset: int = 0) -> None:
        """vkCmdDispatchIndirect; the command is 3 uint32s (x, y, z)."""
        ...

# ---------------------------------------------------------------------------
# Pass builder
# ---------------------------------------------------------------------------

class PassBuilder:
    """Declares one pass. Every method returns the builder for chaining."""

    @property
    def handle(self) -> PassHandle: ...

    def type(self, type: PassType) -> PassBuilder: ...

    @overload
    def vert_shader(self, spirv: bytes) -> PassBuilder:
        """Set the vertex shader from raw SPIR-V bytes."""
        ...
    @overload
    def vert_shader(self, path: str | os.PathLike[str]) -> PassBuilder:
        """Set the vertex shader. Pass a path (.vert → GLSL compiled on-the-fly, .spv → SPIR-V)."""
        ...

    @overload
    def frag_shader(self, spirv: bytes) -> PassBuilder:
        """Set the fragment shader from raw SPIR-V bytes."""
        ...
    @overload
    def frag_shader(self, path: str | os.PathLike[str]) -> PassBuilder:
        """Set the fragment shader. Pass a path (.frag → GLSL compiled on-the-fly, .spv → SPIR-V)."""
        ...

    @overload
    def compute_shader(self, spirv: bytes) -> PassBuilder:
        """Set the compute shader from raw SPIR-V bytes."""
        ...
    @overload
    def compute_shader(self, path: str | os.PathLike[str]) -> PassBuilder:
        """Set the compute shader. Pass a path (.comp → GLSL compiled on-the-fly, .spv → SPIR-V)."""
        ...

    def push_constant_size(self, size: int, stages: Stage) -> PassBuilder: ...
    def topology(self, topology: Topology) -> PassBuilder: ...

    def vertex_layout(
        self,
        bindings: Sequence[VertexBinding],
        attributes: Sequence[VertexAttribute],
    ) -> PassBuilder: ...

    def blend(self, mode: BlendMode) -> PassBuilder:
        """Blend mode for all color attachments."""
        ...

    def samples(self, count: int) -> PassBuilder:
        """Enable MSAA for this pass (typically 4); attachments are resolved automatically."""
        ...

    def polygon_mode(self, mode: PolygonMode) -> PassBuilder:
        """FILL (default), LINE (wireframe) or POINT."""
        ...

    def cull(
        self,
        mode: CullMode,
        front_face: FrontFace = FrontFace.COUNTER_CLOCKWISE,
    ) -> PassBuilder:
        """Default: BACK for geometry passes, NONE for fullscreen ones."""
        ...

    def depth(
        self,
        test: bool,
        write: bool,
        compare: CompareOp = CompareOp.LESS,
    ) -> PassBuilder:
        """Default: test and write on (compare LESS) exactly when the pass has a depth attachment."""
        ...

    def depth_bias(self, constant: float, slope: float = 0.0) -> PassBuilder:
        """Offset rasterized depth, e.g. negative values to draw a wireframe over its own solid surface."""
        ...

    def sampled_image(self, binding: int, image: ImageHandle, stages: Stage) -> PassBuilder: ...
    def sampled_depth(self, binding: int, image: ImageHandle, stages: Stage) -> PassBuilder: ...
    def sampled_image_array(self, binding: int, images: ImageHandle, count: int, stages: Stage) -> PassBuilder:
        """Bind the first `count` elements of an image array (see ResourceRegistry.upload_array_image) as
        `uniform sampler2D name[count]`."""
        ...
    def storage_image_read(self, binding: int, image: ImageHandle, stages: Stage) -> PassBuilder: ...
    def storage_image_write(self, binding: int, image: ImageHandle, stages: Stage) -> PassBuilder: ...
    def storage_image_read_write(self, binding: int, image: ImageHandle, stages: Stage) -> PassBuilder: ...
    def uniform_buffer(self, binding: int, buffer: BufferHandle, stages: Stage) -> PassBuilder: ...
    def storage_buffer_read(self, binding: int, buffer: BufferHandle, stages: Stage) -> PassBuilder: ...
    def storage_buffer_write(self, binding: int, buffer: BufferHandle, stages: Stage) -> PassBuilder: ...
    def storage_buffer_read_write(self, binding: int, buffer: BufferHandle, stages: Stage) -> PassBuilder: ...
    def vertex_buffer(self, binding: int, buffer: BufferHandle) -> PassBuilder: ...
    def index_buffer(self, buffer: BufferHandle) -> PassBuilder: ...

    def indirect_buffer(self, buffer: BufferHandle) -> PassBuilder:
        """Declare a buffer of draw/dispatch arguments for PassContext.draw_indirect() and friends."""
        ...

    def runs_last(self) -> PassBuilder:
        """Order this pass after every other pass sharing a resource with it, even ones declared later."""
        ...

    def color_attachment(
        self,
        image: ImageHandle,
        format: Format,
        load_op: LoadOp = LoadOp.CLEAR,
        clear_color: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 1.0),
        extent: Extent = ...,
    ) -> PassBuilder: ...

    def depth_attachment(
        self,
        image: ImageHandle,
        format: Format = Format.D32_SFLOAT,
        load_op: LoadOp = LoadOp.CLEAR,
        clear_depth: float = 1.0,
        extent: Extent = ...,
    ) -> PassBuilder: ...

    @overload
    def depends_on(self, dependency: PassHandle) -> PassBuilder: ...
    @overload
    def depends_on(self, dependencies: Sequence[PassHandle]) -> PassBuilder: ...

    def execute(self, callback: Callable[[PassContext], None]) -> PassBuilder:
        """Record this pass's commands: callback(ctx: PassContext), called every frame."""
        ...

# ---------------------------------------------------------------------------
# Frame graph
# ---------------------------------------------------------------------------

class FrameGraph:
    def add_pass(self, name: str) -> PassBuilder:
        """Start declaring a pass; passes run in dependency order, derived from the resources they use."""
        ...

    def image(self, name: str) -> ImageHandle:
        """Handle for a named image. Use lr.SWAPCHAIN for the window's back buffer."""
        ...

    def buffer(self, name: str) -> BufferHandle:
        """Handle for a named buffer."""
        ...

    def compile(self) -> None:
        """Rebuild pipelines and barriers after changing passes while running."""
        ...

    @property
    def needs_recompile(self) -> bool: ...

    @property
    def compile_count(self) -> int:
        """How many times the graph has been compiled."""
        ...

    def debug_dump(self) -> None: ...

# ---------------------------------------------------------------------------
# Resource registry
# ---------------------------------------------------------------------------

class ResourceRegistry:
    """Named GPU buffers and images. Passes refer to them by name via FrameGraph.buffer()/image()."""

    @property
    def extent(self) -> tuple[int, int]:
        """Current swapchain-sized extent as (width, height)."""
        ...

    def upload_buffer(self, name: str, data: Buffer, usage: BufferUsage) -> None:
        """Create a GPU-only buffer sized to `data` and upload it before the next frame."""
        ...

    def reupload_buffer(self, name: str, data: Buffer) -> None:
        """Overwrite an uploaded buffer; `data` must fit its original size."""
        ...

    def register_static_buffer(self, name: str, size: int, usage: BufferUsage) -> None:
        """Create an uninitialised GPU-only buffer (e.g. compute scratch)."""
        ...

    def register_dynamic_buffer(self, name: str, size: int, usage: BufferUsage) -> None:
        """Create a CPU-writable buffer for per-frame data such as uniforms; fill it with update_buffer()."""
        ...

    def update_buffer(self, name: str, data: Buffer) -> None:
        """Write `data` into a dynamic buffer (call from an on_update callback)."""
        ...

    def register_image(
        self,
        name: str,
        format: Format,
        usage: ImageUsage,
        extent: Extent = ...,
    ) -> None:
        """Create a transient image, reallocated when the window resizes."""
        ...

    def upload_image(
        self,
        name: str,
        data: Buffer,
        format: Format,
        generate_mipmaps: bool = False,
    ) -> None:
        """Create a sampled image from an array shaped (height, width[, channels])."""
        ...

    def upload_array_image(
        self,
        array_name: str,
        index: int,
        data: Buffer,
        format: Format,
        generate_mipmaps: bool = False,
    ) -> None:
        """Upload one element of an image array (elements may differ in size), for sampled_image_array():
        how a single pass picks a different texture per draw, as the engine's GeometryPass does."""
        ...

    def replace_image(
        self,
        name: str,
        data: Buffer,
        format: Format,
        generate_mipmaps: bool = False,
    ) -> None:
        """Replace an image created by upload_image() (any size/format). Safe while running: the old image
        is kept until in-flight frames finish, and passes sampling it recompile on the next frame."""
        ...

    def replace_buffer(self, name: str, data: Buffer, usage: BufferUsage) -> None:
        """Replace a buffer created by upload_buffer() with new contents of any size. Safe while running."""
        ...

    def replace_dynamic_buffer(self, name: str, size: int, usage: BufferUsage) -> None:
        """Reallocate a buffer created by register_dynamic_buffer() at a new size (contents start undefined).
        Same safety as replace_buffer()."""
        ...

    def read_buffer(self, name: str) -> NDArray[numpy.uint8]:
        """Copy a buffer back to the CPU as a uint8 numpy array (use .view(np.float32) etc.), as of the last
        submitted frame. Waits for the GPU to go idle: meant for tests and debugging, not every frame."""
        ...

    def has_buffer(self, name: str) -> bool: ...
    def has_image(self, name: str) -> bool: ...

# ---------------------------------------------------------------------------
# Viewer
# ---------------------------------------------------------------------------

class Input:
    """Keyboard and mouse state, updated once per frame before on_update. It reports the raw state even
    over UI; check lr.gui.want_capture_mouse() to leave the mouse to ImGui."""

    def is_key_down(self, key: Key) -> bool: ...
    def is_mouse_down(self, button: MouseButton) -> bool: ...
    @property
    def mouse_position(self) -> tuple[float, float]:
        """Cursor position in window pixels, (x, y)."""
        ...
    @property
    def mouse_delta(self) -> tuple[float, float]:
        """Cursor movement since the previous frame, (dx, dy) in pixels."""
        ...
    @property
    def scroll_delta(self) -> float:
        """Scroll-wheel movement since the previous frame."""
        ...
    @property
    def shift(self) -> bool: ...
    @property
    def ctrl(self) -> bool: ...
    @property
    def alt(self) -> bool: ...

class CallbackConnection:
    """A scoped callback registration. Keep it alive while the callback is needed."""

    def disconnect(self) -> None: ...

class Viewer:
    """Window + Vulkan device + frame graph. Declare passes, then call run(), or call step() in your own
    loop."""

    def __init__(
        self,
        title: str = "lr",
        width: int = 1600,
        height: int = 900,
        validation: bool = True,
        raise_validation_errors: bool = True,
        gui: bool = True,
    ) -> None:
        """With validation on (the default), a validation-layer error closes the window and run() raises
        VulkanValidationError; pass raise_validation_errors=False to only log them. gui=False creates no
        ImGui context: on_gui() raises and nothing is drawn over your frame."""
        ...

    @property
    def gui(self) -> bool:
        """Whether this Viewer has ImGui (see the gui argument)."""
        ...

    @property
    def frame_graph(self) -> FrameGraph: ...

    @property
    def resources(self) -> ResourceRegistry: ...

    @property
    def swapchain_format(self) -> Format: ...

    def on_update(self, callback: Callable[[float, tuple[int, int]], None]) -> CallbackConnection:
        """Register callback(dt, extent) before rendering. Keep the returned connection alive."""
        ...

    def on_late_update(self, callback: Callable[[float, tuple[int, int]], None]) -> CallbackConnection:
        """Like on_update, but after every on_update callback. Keep the connection alive."""
        ...

    def on_gui(self, callback: Callable[[], None]) -> CallbackConnection:
        """Register the per-frame GUI callback. Keep the returned connection alive."""
        ...

    @property
    def input(self) -> Input:
        """Keyboard and mouse state for this window."""
        ...

    def run(self) -> None:
        """Compile the frame graph and run frames until the window closes. An exception raised in any
        callback closes the window and is re-raised here. Once the window has closed, its callbacks are
        released: a Viewer runs once."""
        ...

    def step(self) -> bool:
        """Render one frame (compiling the frame graph on the first call) and return True, or False once
        the window has closed: `while viewer.step(): ...` lets your code own the loop. The window only
        responds while it is being stepped. Callbacks run as with run(); an exception raised in one
        closes the window and is re-raised from this step. Once the window has closed, its callbacks
        are released."""
        ...

    @property
    def is_open(self) -> bool:
        """True until the window has closed."""
        ...

    def close(self) -> None:
        """Close the window after the current frame (run() returns, step() returns False)."""
        ...

class OrbitCamera:
    """The engine's orbit camera (SphericalCameraController + Camera), with the C++ renderer's controls:
    middle-drag orbits, Shift + middle-drag pans, the scroll wheel zooms and R resets. Ignores the mouse
    while it is over ImGui UI. Call update() once per frame, then use matrices(extent) for a
    `mat4 view; mat4 proj;` uniform block."""

    def __init__(self, viewer: Viewer) -> None: ...
    def update(self, dt: float) -> None:
        """Apply this frame's input (from on_update)."""
        ...
    def view_matrix(self) -> NDArray[numpy.float32]:
        """4x4 float32 view matrix (row-major numpy, acting on column vectors)."""
        ...
    def projection_matrix(self, aspect: float) -> NDArray[numpy.float32]:
        """4x4 float32 projection: Vulkan clip space, depth in [0, 1], Y flipped — as the engine uses."""
        ...
    def matrices(self, extent: tuple[int, int]) -> NDArray[numpy.float32]:
        """view and projection for a (width, height) extent, packed for a `mat4 view; mat4 proj;` block."""
        ...
    @property
    def position(self) -> tuple[float, float, float]:
        """Camera position in world space."""
        ...
    @property
    def target(self) -> tuple[float, float, float]:
        """The point orbited around."""
        ...
    @target.setter
    def target(self, value: Sequence[float]) -> None: ...
    @property
    def radius(self) -> float:
        """Distance from the target (clamped to [0.01, 1000])."""
        ...
    @radius.setter
    def radius(self, value: float) -> None: ...
    @property
    def azimuth(self) -> float:
        """Radians around +Y; 0 places the camera on the target's +Z side."""
        ...
    @azimuth.setter
    def azimuth(self, value: float) -> None: ...
    @property
    def elevation(self) -> float:
        """Radians above the horizontal (clamped to ±89°)."""
        ...
    @elevation.setter
    def elevation(self, value: float) -> None: ...
    @property
    def fov_y_degrees(self) -> float: ...
    @fov_y_degrees.setter
    def fov_y_degrees(self, value: float) -> None: ...
    @property
    def near_plane(self) -> float: ...
    @near_plane.setter
    def near_plane(self, value: float) -> None: ...
    @property
    def far_plane(self) -> float: ...
    @far_plane.setter
    def far_plane(self, value: float) -> None: ...
    @property
    def orthographic(self) -> bool:
        """Orthographic instead of perspective projection (height set by ortho_height)."""
        ...
    @orthographic.setter
    def orthographic(self, value: bool) -> None: ...
    @property
    def ortho_height(self) -> float: ...
    @ortho_height.setter
    def ortho_height(self, value: float) -> None: ...

# ---------------------------------------------------------------------------
# Shader utilities
# ---------------------------------------------------------------------------

class ShaderCompileError(Exception): ...
class ShaderInterfaceError(RuntimeError): ...
class VulkanValidationError(RuntimeError): ...

def compile_glsl(
    path: os.PathLike,
    stage: ShaderStage | None = None,
    include_dirs: Sequence[os.PathLike] = (),
) -> bytes:
    """Compile a GLSL file to SPIR-V bytes. Stage is inferred from .vert/.frag/.comp unless given."""
    ...

def compile_glsl_source(
    source: str,
    stage: ShaderStage,
    name: str = "<source>",
    include_dirs: Sequence[os.PathLike] = (),
) -> bytes:
    """Compile GLSL source text to SPIR-V bytes."""
    ...

SWAPCHAIN: str
"""Frame-graph name of the window's current image: draw to fg.image(lr.SWAPCHAIN) to show something."""
SHADER_DIR: pathlib.Path
ASSET_DIR: pathlib.Path
